/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.md;

public class BarDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BarDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BarDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmdataJNI.delete_BarDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmdataJNI.BarDataArray_status(swigCPtr, this);
  }

  public Bar data() {
    long cPtr = gmdataJNI.BarDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new Bar(cPtr, false);
  }

  public int count() {
    return gmdataJNI.BarDataArray_count(swigCPtr, this);
  }

  public Bar at(int i) {
    return new Bar(gmdataJNI.BarDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmdataJNI.BarDataArray_release(swigCPtr, this);
  }

}
