/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.md;

public class Data {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Data(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Data obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmdataJNI.delete_Data(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    gmdataJNI.Data_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    gmdataJNI.Data_change_ownership(this, swigCPtr, true);
  }

  public Data(String token) {
    this(gmdataJNI.new_Data__SWIG_0(token), true);
    gmdataJNI.Data_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public Data() {
    this(gmdataJNI.new_Data__SWIG_1(), true);
    gmdataJNI.Data_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void set_token(String token) {
    gmdataJNI.Data_set_token(swigCPtr, this, token);
  }

  public void set_endpoint(String addr) {
    gmdataJNI.Data_set_endpoint(swigCPtr, this, addr);
  }

  public int start() {
    return gmdataJNI.Data_start(swigCPtr, this);
  }

  public void stop() {
    gmdataJNI.Data_stop(swigCPtr, this);
  }

  public int subscribe(String symbols, String frequency, boolean unsubscribe_previous) {
    return gmdataJNI.Data_subscribe__SWIG_0(swigCPtr, this, symbols, frequency, unsubscribe_previous);
  }

  public int subscribe(String symbols, String frequency) {
    return gmdataJNI.Data_subscribe__SWIG_1(swigCPtr, this, symbols, frequency);
  }

  public int unsubscribe(String symbols, String frequency) {
    return gmdataJNI.Data_unsubscribe(swigCPtr, this, symbols, frequency);
  }

  public TickDataArray current(String symbols) {
    long cPtr = gmdataJNI.Data_current(swigCPtr, this, symbols);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmdataJNI.Data_history_ticks__SWIG_0(swigCPtr, this, symbols, start_time, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmdataJNI.Data_history_ticks__SWIG_1(swigCPtr, this, symbols, start_time, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmdataJNI.Data_history_ticks__SWIG_2(swigCPtr, this, symbols, start_time, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks(String symbols, String start_time, String end_time, int adjust) {
    long cPtr = gmdataJNI.Data_history_ticks__SWIG_3(swigCPtr, this, symbols, start_time, end_time, adjust);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks(String symbols, String start_time, String end_time) {
    long cPtr = gmdataJNI.Data_history_ticks__SWIG_4(swigCPtr, this, symbols, start_time, end_time);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public BarDataArray history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmdataJNI.Data_history_bars__SWIG_0(swigCPtr, this, symbols, frequency, start_time, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmdataJNI.Data_history_bars__SWIG_1(swigCPtr, this, symbols, frequency, start_time, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmdataJNI.Data_history_bars__SWIG_2(swigCPtr, this, symbols, frequency, start_time, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars(String symbols, String frequency, String start_time, String end_time, int adjust) {
    long cPtr = gmdataJNI.Data_history_bars__SWIG_3(swigCPtr, this, symbols, frequency, start_time, end_time, adjust);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars(String symbols, String frequency, String start_time, String end_time) {
    long cPtr = gmdataJNI.Data_history_bars__SWIG_4(swigCPtr, this, symbols, frequency, start_time, end_time);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_0(swigCPtr, this, symbols, n, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_1(swigCPtr, this, symbols, n, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_2(swigCPtr, this, symbols, n, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n, String end_time, int adjust) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_3(swigCPtr, this, symbols, n, end_time, adjust);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n, String end_time) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_4(swigCPtr, this, symbols, n, end_time);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public TickDataArray history_ticks_n(String symbols, int n) {
    long cPtr = gmdataJNI.Data_history_ticks_n__SWIG_5(swigCPtr, this, symbols, n);
    return (cPtr == 0) ? null : new TickDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_0(swigCPtr, this, symbols, frequency, n, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_1(swigCPtr, this, symbols, frequency, n, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_2(swigCPtr, this, symbols, frequency, n, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n, String end_time, int adjust) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_3(swigCPtr, this, symbols, frequency, n, end_time, adjust);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n, String end_time) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_4(swigCPtr, this, symbols, frequency, n, end_time);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public BarDataArray history_bars_n(String symbols, String frequency, int n) {
    long cPtr = gmdataJNI.Data_history_bars_n__SWIG_5(swigCPtr, this, symbols, frequency, n);
    return (cPtr == 0) ? null : new BarDataArray(cPtr, false);
  }

  public DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter, String order_by, int limit) {
    long cPtr = gmdataJNI.Data_get_fundamentals__SWIG_0(swigCPtr, this, table, symbols, start_date, end_date, fields, filter, order_by, limit);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter, String order_by) {
    long cPtr = gmdataJNI.Data_get_fundamentals__SWIG_1(swigCPtr, this, table, symbols, start_date, end_date, fields, filter, order_by);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter) {
    long cPtr = gmdataJNI.Data_get_fundamentals__SWIG_2(swigCPtr, this, table, symbols, start_date, end_date, fields, filter);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields) {
    long cPtr = gmdataJNI.Data_get_fundamentals__SWIG_3(swigCPtr, this, table, symbols, start_date, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n, String filter, String order_by) {
    long cPtr = gmdataJNI.Data_get_fundamentals_n__SWIG_0(swigCPtr, this, table, symbols, end_date, fields, n, filter, order_by);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n, String filter) {
    long cPtr = gmdataJNI.Data_get_fundamentals_n__SWIG_1(swigCPtr, this, table, symbols, end_date, fields, n, filter);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n) {
    long cPtr = gmdataJNI.Data_get_fundamentals_n__SWIG_2(swigCPtr, this, table, symbols, end_date, fields, n);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields) {
    long cPtr = gmdataJNI.Data_get_fundamentals_n__SWIG_3(swigCPtr, this, table, symbols, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instruments(String exchanges, String sec_types, String fields) {
    long cPtr = gmdataJNI.Data_get_instruments__SWIG_0(swigCPtr, this, exchanges, sec_types, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instruments(String exchanges, String sec_types) {
    long cPtr = gmdataJNI.Data_get_instruments__SWIG_1(swigCPtr, this, exchanges, sec_types);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instruments(String exchanges) {
    long cPtr = gmdataJNI.Data_get_instruments__SWIG_2(swigCPtr, this, exchanges);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instruments() {
    long cPtr = gmdataJNI.Data_get_instruments__SWIG_3(swigCPtr, this);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_history_instruments(String symbols, String start_date, String end_date, String fields) {
    long cPtr = gmdataJNI.Data_get_history_instruments__SWIG_0(swigCPtr, this, symbols, start_date, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_history_instruments(String symbols, String start_date, String end_date) {
    long cPtr = gmdataJNI.Data_get_history_instruments__SWIG_1(swigCPtr, this, symbols, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types, String names, String fields) {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_0(swigCPtr, this, symbols, exchanges, sec_types, names, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types, String names) {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_1(swigCPtr, this, symbols, exchanges, sec_types, names);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types) {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_2(swigCPtr, this, symbols, exchanges, sec_types);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos(String symbols, String exchanges) {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_3(swigCPtr, this, symbols, exchanges);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos(String symbols) {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_4(swigCPtr, this, symbols);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_instrumentinfos() {
    long cPtr = gmdataJNI.Data_get_instrumentinfos__SWIG_5(swigCPtr, this);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_constituents(String index, String trade_date) {
    long cPtr = gmdataJNI.Data_get_constituents__SWIG_0(swigCPtr, this, index, trade_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_constituents(String index) {
    long cPtr = gmdataJNI.Data_get_constituents__SWIG_1(swigCPtr, this, index);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public SymbolDataArray get_industry(String code) {
    long cPtr = gmdataJNI.Data_get_industry(swigCPtr, this, code);
    return (cPtr == 0) ? null : new SymbolDataArray(cPtr, false);
  }

  public SymbolDataArray get_concept(String code) {
    long cPtr = gmdataJNI.Data_get_concept(swigCPtr, this, code);
    return (cPtr == 0) ? null : new SymbolDataArray(cPtr, false);
  }

  public TradingDateDataArray get_trading_dates(String exchange, String start_date, String end_date) {
    long cPtr = gmdataJNI.Data_get_trading_dates(swigCPtr, this, exchange, start_date, end_date);
    return (cPtr == 0) ? null : new TradingDateDataArray(cPtr, false);
  }

  public int get_previous_trading_date(String exchange, String date, String output_date) {
    return gmdataJNI.Data_get_previous_trading_date(swigCPtr, this, exchange, date, output_date);
  }

  public int get_next_trading_date(String exchange, String date, String output_date) {
    return gmdataJNI.Data_get_next_trading_date(swigCPtr, this, exchange, date, output_date);
  }

  public DataSet get_dividend(String symbol, String start_date, String end_date) {
    long cPtr = gmdataJNI.Data_get_dividend(swigCPtr, this, symbol, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public DataSet get_continuous_contracts(String csymbol, String start_date, String end_date) {
    long cPtr = gmdataJNI.Data_get_continuous_contracts(swigCPtr, this, csymbol, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public void on_tick(Tick tick) {
    if (getClass() == Data.class) gmdataJNI.Data_on_tick(swigCPtr, this, Tick.getCPtr(tick), tick); else gmdataJNI.Data_on_tickSwigExplicitData(swigCPtr, this, Tick.getCPtr(tick), tick);
  }

  public void on_bar(Bar bar) {
    if (getClass() == Data.class) gmdataJNI.Data_on_bar(swigCPtr, this, Bar.getCPtr(bar), bar); else gmdataJNI.Data_on_barSwigExplicitData(swigCPtr, this, Bar.getCPtr(bar), bar);
  }

  public void on_error(int error_code, String error_msg) {
    if (getClass() == Data.class) gmdataJNI.Data_on_error(swigCPtr, this, error_code, error_msg); else gmdataJNI.Data_on_errorSwigExplicitData(swigCPtr, this, error_code, error_msg);
  }

  public void on_market_data_connected() {
    if (getClass() == Data.class) gmdataJNI.Data_on_market_data_connected(swigCPtr, this); else gmdataJNI.Data_on_market_data_connectedSwigExplicitData(swigCPtr, this);
  }

  public void on_market_data_disconnected() {
    if (getClass() == Data.class) gmdataJNI.Data_on_market_data_disconnected(swigCPtr, this); else gmdataJNI.Data_on_market_data_disconnectedSwigExplicitData(swigCPtr, this);
  }

}
