/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.md;

public class gmdata {
  public static long getLEN_DATA_SYMBOL() {
    return gmdataJNI.LEN_DATA_SYMBOL_get();
  }

  public static long getLEN_EXCHANGE() {
    return gmdataJNI.LEN_EXCHANGE_get();
  }

  public static long getLEN_ISO_DATATIME() {
    return gmdataJNI.LEN_ISO_DATATIME_get();
  }

  public static long getLEN_FREQUENCY() {
    return gmdataJNI.LEN_FREQUENCY_get();
  }

  public static long getDEPTH_OF_QUOTE() {
    return gmdataJNI.DEPTH_OF_QUOTE_get();
  }

}
