/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.md;

public class gmdataJNI {
  public final static native long LEN_DATA_SYMBOL_get();
  public final static native long LEN_EXCHANGE_get();
  public final static native long LEN_ISO_DATATIME_get();
  public final static native long LEN_FREQUENCY_get();
  public final static native long DEPTH_OF_QUOTE_get();
  public final static native void Bar_symbol_set(long jarg1, Bar jarg1_, String jarg2);
  public final static native String Bar_symbol_get(long jarg1, Bar jarg1_);
  public final static native void Bar_bob_set(long jarg1, Bar jarg1_, double jarg2);
  public final static native double Bar_bob_get(long jarg1, Bar jarg1_);
  public final static native void Bar_eob_set(long jarg1, Bar jarg1_, double jarg2);
  public final static native double Bar_eob_get(long jarg1, Bar jarg1_);
  public final static native void Bar_open_set(long jarg1, Bar jarg1_, float jarg2);
  public final static native float Bar_open_get(long jarg1, Bar jarg1_);
  public final static native void Bar_close_set(long jarg1, Bar jarg1_, float jarg2);
  public final static native float Bar_close_get(long jarg1, Bar jarg1_);
  public final static native void Bar_high_set(long jarg1, Bar jarg1_, float jarg2);
  public final static native float Bar_high_get(long jarg1, Bar jarg1_);
  public final static native void Bar_low_set(long jarg1, Bar jarg1_, float jarg2);
  public final static native float Bar_low_get(long jarg1, Bar jarg1_);
  public final static native void Bar_volume_set(long jarg1, Bar jarg1_, double jarg2);
  public final static native double Bar_volume_get(long jarg1, Bar jarg1_);
  public final static native void Bar_amount_set(long jarg1, Bar jarg1_, double jarg2);
  public final static native double Bar_amount_get(long jarg1, Bar jarg1_);
  public final static native void Bar_pre_close_set(long jarg1, Bar jarg1_, float jarg2);
  public final static native float Bar_pre_close_get(long jarg1, Bar jarg1_);
  public final static native void Bar_position_set(long jarg1, Bar jarg1_, long jarg2);
  public final static native long Bar_position_get(long jarg1, Bar jarg1_);
  public final static native void Bar_frequency_set(long jarg1, Bar jarg1_, String jarg2);
  public final static native String Bar_frequency_get(long jarg1, Bar jarg1_);
  public final static native long new_Bar();
  public final static native void delete_Bar(long jarg1);
  public final static native void Quote_bid_price_set(long jarg1, Quote jarg1_, float jarg2);
  public final static native float Quote_bid_price_get(long jarg1, Quote jarg1_);
  public final static native void Quote_bid_volume_set(long jarg1, Quote jarg1_, long jarg2);
  public final static native long Quote_bid_volume_get(long jarg1, Quote jarg1_);
  public final static native void Quote_ask_price_set(long jarg1, Quote jarg1_, float jarg2);
  public final static native float Quote_ask_price_get(long jarg1, Quote jarg1_);
  public final static native void Quote_ask_volume_set(long jarg1, Quote jarg1_, long jarg2);
  public final static native long Quote_ask_volume_get(long jarg1, Quote jarg1_);
  public final static native long new_Quote();
  public final static native void delete_Quote(long jarg1);
  public final static native void Tick_symbol_set(long jarg1, Tick jarg1_, String jarg2);
  public final static native String Tick_symbol_get(long jarg1, Tick jarg1_);
  public final static native void Tick_created_at_set(long jarg1, Tick jarg1_, double jarg2);
  public final static native double Tick_created_at_get(long jarg1, Tick jarg1_);
  public final static native void Tick_price_set(long jarg1, Tick jarg1_, float jarg2);
  public final static native float Tick_price_get(long jarg1, Tick jarg1_);
  public final static native void Tick_open_set(long jarg1, Tick jarg1_, float jarg2);
  public final static native float Tick_open_get(long jarg1, Tick jarg1_);
  public final static native void Tick_high_set(long jarg1, Tick jarg1_, float jarg2);
  public final static native float Tick_high_get(long jarg1, Tick jarg1_);
  public final static native void Tick_low_set(long jarg1, Tick jarg1_, float jarg2);
  public final static native float Tick_low_get(long jarg1, Tick jarg1_);
  public final static native void Tick_cum_volume_set(long jarg1, Tick jarg1_, double jarg2);
  public final static native double Tick_cum_volume_get(long jarg1, Tick jarg1_);
  public final static native void Tick_cum_amount_set(long jarg1, Tick jarg1_, double jarg2);
  public final static native double Tick_cum_amount_get(long jarg1, Tick jarg1_);
  public final static native void Tick_cum_position_set(long jarg1, Tick jarg1_, long jarg2);
  public final static native long Tick_cum_position_get(long jarg1, Tick jarg1_);
  public final static native void Tick_last_amount_set(long jarg1, Tick jarg1_, double jarg2);
  public final static native double Tick_last_amount_get(long jarg1, Tick jarg1_);
  public final static native void Tick_last_volume_set(long jarg1, Tick jarg1_, int jarg2);
  public final static native int Tick_last_volume_get(long jarg1, Tick jarg1_);
  public final static native void Tick_trade_type_set(long jarg1, Tick jarg1_, int jarg2);
  public final static native int Tick_trade_type_get(long jarg1, Tick jarg1_);
  public final static native void Tick_quotes_set(long jarg1, Tick jarg1_, long jarg2, Quote jarg2_);
  public final static native long Tick_quotes_get(long jarg1, Tick jarg1_);
  public final static native long Tick_getQuoteAt(long jarg1, Tick jarg1_, int jarg2);
  public final static native long new_Tick();
  public final static native void delete_Tick(long jarg1);
  public final static native int DataSet_status(long jarg1, DataSet jarg1_);
  public final static native boolean DataSet_is_end(long jarg1, DataSet jarg1_);
  public final static native void DataSet_next(long jarg1, DataSet jarg1_);
  public final static native int DataSet_get_integer(long jarg1, DataSet jarg1_, String jarg2);
  public final static native long DataSet_get_long_integer(long jarg1, DataSet jarg1_, String jarg2);
  public final static native double DataSet_get_real(long jarg1, DataSet jarg1_, String jarg2);
  public final static native String DataSet_get_string(long jarg1, DataSet jarg1_, String jarg2);
  public final static native void DataSet_release(long jarg1, DataSet jarg1_);
  public final static native String DataSet_debug_string(long jarg1, DataSet jarg1_);
  public final static native void delete_DataSet(long jarg1);
  public final static native long new_Data__SWIG_0(String jarg1);
  public final static native long new_Data__SWIG_1();
  public final static native void delete_Data(long jarg1);
  public final static native void Data_set_token(long jarg1, Data jarg1_, String jarg2);
  public final static native void Data_set_endpoint(long jarg1, Data jarg1_, String jarg2);
  public final static native int Data_start(long jarg1, Data jarg1_);
  public final static native void Data_stop(long jarg1, Data jarg1_);
  public final static native int Data_subscribe__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, boolean jarg4);
  public final static native int Data_subscribe__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3);
  public final static native int Data_unsubscribe(long jarg1, Data jarg1_, String jarg2, String jarg3);
  public final static native long Data_current(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_history_ticks__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, int jarg5, String jarg6, boolean jarg7, String jarg8);
  public final static native long Data_history_ticks__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, int jarg5, String jarg6, boolean jarg7);
  public final static native long Data_history_ticks__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, int jarg5, String jarg6);
  public final static native long Data_history_ticks__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, int jarg5);
  public final static native long Data_history_ticks__SWIG_4(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_history_bars__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6, String jarg7, boolean jarg8, String jarg9);
  public final static native long Data_history_bars__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6, String jarg7, boolean jarg8);
  public final static native long Data_history_bars__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6, String jarg7);
  public final static native long Data_history_bars__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6);
  public final static native long Data_history_bars__SWIG_4(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long Data_history_ticks_n__SWIG_0(long jarg1, Data jarg1_, String jarg2, int jarg3, String jarg4, int jarg5, String jarg6, boolean jarg7, String jarg8);
  public final static native long Data_history_ticks_n__SWIG_1(long jarg1, Data jarg1_, String jarg2, int jarg3, String jarg4, int jarg5, String jarg6, boolean jarg7);
  public final static native long Data_history_ticks_n__SWIG_2(long jarg1, Data jarg1_, String jarg2, int jarg3, String jarg4, int jarg5, String jarg6);
  public final static native long Data_history_ticks_n__SWIG_3(long jarg1, Data jarg1_, String jarg2, int jarg3, String jarg4, int jarg5);
  public final static native long Data_history_ticks_n__SWIG_4(long jarg1, Data jarg1_, String jarg2, int jarg3, String jarg4);
  public final static native long Data_history_ticks_n__SWIG_5(long jarg1, Data jarg1_, String jarg2, int jarg3);
  public final static native long Data_history_bars_n__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4, String jarg5, int jarg6, String jarg7, boolean jarg8, String jarg9);
  public final static native long Data_history_bars_n__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4, String jarg5, int jarg6, String jarg7, boolean jarg8);
  public final static native long Data_history_bars_n__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4, String jarg5, int jarg6, String jarg7);
  public final static native long Data_history_bars_n__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4, String jarg5, int jarg6);
  public final static native long Data_history_bars_n__SWIG_4(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4, String jarg5);
  public final static native long Data_history_bars_n__SWIG_5(long jarg1, Data jarg1_, String jarg2, String jarg3, int jarg4);
  public final static native long Data_get_fundamentals__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8, int jarg9);
  public final static native long Data_get_fundamentals__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7, String jarg8);
  public final static native long Data_get_fundamentals__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7);
  public final static native long Data_get_fundamentals__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native long Data_get_fundamentals_n__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6, String jarg7, String jarg8);
  public final static native long Data_get_fundamentals_n__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6, String jarg7);
  public final static native long Data_get_fundamentals_n__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, int jarg6);
  public final static native long Data_get_fundamentals_n__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long Data_get_instruments__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_get_instruments__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3);
  public final static native long Data_get_instruments__SWIG_2(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_get_instruments__SWIG_3(long jarg1, Data jarg1_);
  public final static native long Data_get_history_instruments__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long Data_get_history_instruments__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_get_instrumentinfos__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6);
  public final static native long Data_get_instrumentinfos__SWIG_1(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long Data_get_instrumentinfos__SWIG_2(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_get_instrumentinfos__SWIG_3(long jarg1, Data jarg1_, String jarg2, String jarg3);
  public final static native long Data_get_instrumentinfos__SWIG_4(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_get_instrumentinfos__SWIG_5(long jarg1, Data jarg1_);
  public final static native long Data_get_constituents__SWIG_0(long jarg1, Data jarg1_, String jarg2, String jarg3);
  public final static native long Data_get_constituents__SWIG_1(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_get_industry(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_get_concept(long jarg1, Data jarg1_, String jarg2);
  public final static native long Data_get_trading_dates(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native int Data_get_previous_trading_date(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native int Data_get_next_trading_date(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_get_dividend(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native long Data_get_continuous_contracts(long jarg1, Data jarg1_, String jarg2, String jarg3, String jarg4);
  public final static native void Data_on_tick(long jarg1, Data jarg1_, long jarg2, Tick jarg2_);
  public final static native void Data_on_tickSwigExplicitData(long jarg1, Data jarg1_, long jarg2, Tick jarg2_);
  public final static native void Data_on_bar(long jarg1, Data jarg1_, long jarg2, Bar jarg2_);
  public final static native void Data_on_barSwigExplicitData(long jarg1, Data jarg1_, long jarg2, Bar jarg2_);
  public final static native void Data_on_error(long jarg1, Data jarg1_, int jarg2, String jarg3);
  public final static native void Data_on_errorSwigExplicitData(long jarg1, Data jarg1_, int jarg2, String jarg3);
  public final static native void Data_on_market_data_connected(long jarg1, Data jarg1_);
  public final static native void Data_on_market_data_connectedSwigExplicitData(long jarg1, Data jarg1_);
  public final static native void Data_on_market_data_disconnected(long jarg1, Data jarg1_);
  public final static native void Data_on_market_data_disconnectedSwigExplicitData(long jarg1, Data jarg1_);
  public final static native void Data_director_connect(Data obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Data_change_ownership(Data obj, long cptr, boolean take_or_release);
  public final static native int BarDataArray_status(long jarg1, BarDataArray jarg1_);
  public final static native long BarDataArray_data(long jarg1, BarDataArray jarg1_);
  public final static native int BarDataArray_count(long jarg1, BarDataArray jarg1_);
  public final static native long BarDataArray_at(long jarg1, BarDataArray jarg1_, int jarg2);
  public final static native void BarDataArray_release(long jarg1, BarDataArray jarg1_);
  public final static native void delete_BarDataArray(long jarg1);
  public final static native int TickDataArray_status(long jarg1, TickDataArray jarg1_);
  public final static native long TickDataArray_data(long jarg1, TickDataArray jarg1_);
  public final static native int TickDataArray_count(long jarg1, TickDataArray jarg1_);
  public final static native long TickDataArray_at(long jarg1, TickDataArray jarg1_, int jarg2);
  public final static native void TickDataArray_release(long jarg1, TickDataArray jarg1_);
  public final static native void delete_TickDataArray(long jarg1);
  public final static native int SymbolDataArray_status(long jarg1, SymbolDataArray jarg1_);
  public final static native long SymbolDataArray_data(long jarg1, SymbolDataArray jarg1_);
  public final static native int SymbolDataArray_count(long jarg1, SymbolDataArray jarg1_);
  public final static native long SymbolDataArray_at(long jarg1, SymbolDataArray jarg1_, int jarg2);
  public final static native void SymbolDataArray_release(long jarg1, SymbolDataArray jarg1_);
  public final static native void delete_SymbolDataArray(long jarg1);
  public final static native int TradingDateDataArray_status(long jarg1, TradingDateDataArray jarg1_);
  public final static native long TradingDateDataArray_data(long jarg1, TradingDateDataArray jarg1_);
  public final static native int TradingDateDataArray_count(long jarg1, TradingDateDataArray jarg1_);
  public final static native long TradingDateDataArray_at(long jarg1, TradingDateDataArray jarg1_, int jarg2);
  public final static native void TradingDateDataArray_release(long jarg1, TradingDateDataArray jarg1_);
  public final static native void delete_TradingDateDataArray(long jarg1);

  public static void SwigDirector_Data_on_tick(Data jself, long tick) {
    jself.on_tick((tick == 0) ? null : new Tick(tick, false));
  }
  public static void SwigDirector_Data_on_bar(Data jself, long bar) {
    jself.on_bar((bar == 0) ? null : new Bar(bar, false));
  }
  public static void SwigDirector_Data_on_error(Data jself, int error_code, String error_msg) {
    jself.on_error(error_code, error_msg);
  }
  public static void SwigDirector_Data_on_market_data_connected(Data jself) {
    jself.on_market_data_connected();
  }
  public static void SwigDirector_Data_on_market_data_disconnected(Data jself) {
    jself.on_market_data_disconnected();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
