/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.md;

public class Tick {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Tick(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tick obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmdataJNI.delete_Tick(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSymbol(String value) {
    gmdataJNI.Tick_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return gmdataJNI.Tick_symbol_get(swigCPtr, this);
  }

  public void setCreated_at(double value) {
    gmdataJNI.Tick_created_at_set(swigCPtr, this, value);
  }

  public double getCreated_at() {
    return gmdataJNI.Tick_created_at_get(swigCPtr, this);
  }

  public void setPrice(float value) {
    gmdataJNI.Tick_price_set(swigCPtr, this, value);
  }

  public float getPrice() {
    return gmdataJNI.Tick_price_get(swigCPtr, this);
  }

  public void setOpen(float value) {
    gmdataJNI.Tick_open_set(swigCPtr, this, value);
  }

  public float getOpen() {
    return gmdataJNI.Tick_open_get(swigCPtr, this);
  }

  public void setHigh(float value) {
    gmdataJNI.Tick_high_set(swigCPtr, this, value);
  }

  public float getHigh() {
    return gmdataJNI.Tick_high_get(swigCPtr, this);
  }

  public void setLow(float value) {
    gmdataJNI.Tick_low_set(swigCPtr, this, value);
  }

  public float getLow() {
    return gmdataJNI.Tick_low_get(swigCPtr, this);
  }

  public void setCum_volume(double value) {
    gmdataJNI.Tick_cum_volume_set(swigCPtr, this, value);
  }

  public double getCum_volume() {
    return gmdataJNI.Tick_cum_volume_get(swigCPtr, this);
  }

  public void setCum_amount(double value) {
    gmdataJNI.Tick_cum_amount_set(swigCPtr, this, value);
  }

  public double getCum_amount() {
    return gmdataJNI.Tick_cum_amount_get(swigCPtr, this);
  }

  public void setCum_position(long value) {
    gmdataJNI.Tick_cum_position_set(swigCPtr, this, value);
  }

  public long getCum_position() {
    return gmdataJNI.Tick_cum_position_get(swigCPtr, this);
  }

  public void setLast_amount(double value) {
    gmdataJNI.Tick_last_amount_set(swigCPtr, this, value);
  }

  public double getLast_amount() {
    return gmdataJNI.Tick_last_amount_get(swigCPtr, this);
  }

  public void setLast_volume(int value) {
    gmdataJNI.Tick_last_volume_set(swigCPtr, this, value);
  }

  public int getLast_volume() {
    return gmdataJNI.Tick_last_volume_get(swigCPtr, this);
  }

  public void setTrade_type(int value) {
    gmdataJNI.Tick_trade_type_set(swigCPtr, this, value);
  }

  public int getTrade_type() {
    return gmdataJNI.Tick_trade_type_get(swigCPtr, this);
  }

  public void setQuotes(Quote value) {
    gmdataJNI.Tick_quotes_set(swigCPtr, this, Quote.getCPtr(value), value);
  }

  public Quote getQuotes() {
    long cPtr = gmdataJNI.Tick_quotes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Quote(cPtr, false);
  }

  public Quote getQuoteAt(int index) {
    return new Quote(gmdataJNI.Tick_getQuoteAt(swigCPtr, this, index), true);
  }

  public Tick() {
    this(gmdataJNI.new_Tick(), true);
  }

}
