/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class AccountState {
  public final static AccountState State_UNKNOWN = new AccountState("State_UNKNOWN", gmsdkJNI.State_UNKNOWN_get());
  public final static AccountState State_CONNECTING = new AccountState("State_CONNECTING", gmsdkJNI.State_CONNECTING_get());
  public final static AccountState State_CONNECTED = new AccountState("State_CONNECTED", gmsdkJNI.State_CONNECTED_get());
  public final static AccountState State_LOGGEDIN = new AccountState("State_LOGGEDIN", gmsdkJNI.State_LOGGEDIN_get());
  public final static AccountState State_DISCONNECTING = new AccountState("State_DISCONNECTING", gmsdkJNI.State_DISCONNECTING_get());
  public final static AccountState State_DISCONNECTED = new AccountState("State_DISCONNECTED", gmsdkJNI.State_DISCONNECTED_get());
  public final static AccountState State_ERROR = new AccountState("State_ERROR", gmsdkJNI.State_ERROR_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AccountState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AccountState.class + " with value " + swigValue);
  }

  private AccountState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AccountState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AccountState(String swigName, AccountState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AccountState[] swigValues = { State_UNKNOWN, State_CONNECTING, State_CONNECTED, State_LOGGEDIN, State_DISCONNECTING, State_DISCONNECTED, State_ERROR };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

