/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm;

public class CashDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CashDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CashDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_CashDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmsdkJNI.CashDataArray_status(swigCPtr, this);
  }

  public Cash data() {
    long cPtr = gmsdkJNI.CashDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new Cash(cPtr, false);
  }

  public int count() {
    return gmsdkJNI.CashDataArray_count(swigCPtr, this);
  }

  public Cash at(int i) {
    return new Cash(gmsdkJNI.CashDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmsdkJNI.CashDataArray_release(swigCPtr, this);
  }

}
