/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class CashPositionChangeReason {
  public final static CashPositionChangeReason CashPositionChangeReason_Unknown = new CashPositionChangeReason("CashPositionChangeReason_Unknown", gmsdkJNI.CashPositionChangeReason_Unknown_get());
  public final static CashPositionChangeReason CashPositionChangeReason_Trade = new CashPositionChangeReason("CashPositionChangeReason_Trade", gmsdkJNI.CashPositionChangeReason_Trade_get());
  public final static CashPositionChangeReason CashPositionChangeReason_Inout = new CashPositionChangeReason("CashPositionChangeReason_Inout", gmsdkJNI.CashPositionChangeReason_Inout_get());
  public final static CashPositionChangeReason CashPositionChangeReason_Dividend = new CashPositionChangeReason("CashPositionChangeReason_Dividend", gmsdkJNI.CashPositionChangeReason_Dividend_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CashPositionChangeReason swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CashPositionChangeReason.class + " with value " + swigValue);
  }

  private CashPositionChangeReason(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CashPositionChangeReason(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CashPositionChangeReason(String swigName, CashPositionChangeReason swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CashPositionChangeReason[] swigValues = { CashPositionChangeReason_Unknown, CashPositionChangeReason_Trade, CashPositionChangeReason_Inout, CashPositionChangeReason_Dividend };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

