/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public class gmsdk implements gmsdkConstants {
  public static String get_version() {
    return gmsdkJNI.get_version();
  }

  public static void set_token(String token) {
    gmsdkJNI.set_token(token);
  }

  public static void set_serv_addr(String addr) {
    gmsdkJNI.set_serv_addr(addr);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t current(String symbols) {
    long cPtr = gmsdkJNI.current(symbols);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmsdkJNI.history_ticks__SWIG_0(symbols, start_time, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmsdkJNI.history_ticks__SWIG_1(symbols, start_time, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks(String symbols, String start_time, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmsdkJNI.history_ticks__SWIG_2(symbols, start_time, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks(String symbols, String start_time, String end_time, int adjust) {
    long cPtr = gmsdkJNI.history_ticks__SWIG_3(symbols, start_time, end_time, adjust);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks(String symbols, String start_time, String end_time) {
    long cPtr = gmsdkJNI.history_ticks__SWIG_4(symbols, start_time, end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmsdkJNI.history_bars__SWIG_0(symbols, frequency, start_time, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmsdkJNI.history_bars__SWIG_1(symbols, frequency, start_time, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars(String symbols, String frequency, String start_time, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmsdkJNI.history_bars__SWIG_2(symbols, frequency, start_time, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars(String symbols, String frequency, String start_time, String end_time, int adjust) {
    long cPtr = gmsdkJNI.history_bars__SWIG_3(symbols, frequency, start_time, end_time, adjust);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars(String symbols, String frequency, String start_time, String end_time) {
    long cPtr = gmsdkJNI.history_bars__SWIG_4(symbols, frequency, start_time, end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_0(symbols, n, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_1(symbols, n, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_2(symbols, n, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n, String end_time, int adjust) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_3(symbols, n, end_time, adjust);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n, String end_time) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_4(symbols, n, end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Tick_t history_ticks_n(String symbols, int n) {
    long cPtr = gmsdkJNI.history_ticks_n__SWIG_5(symbols, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Tick_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended, String fill_missing) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_0(symbols, frequency, n, end_time, adjust, adjust_end_time, skip_suspended, fill_missing);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time, boolean skip_suspended) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_1(symbols, frequency, n, end_time, adjust, adjust_end_time, skip_suspended);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n, String end_time, int adjust, String adjust_end_time) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_2(symbols, frequency, n, end_time, adjust, adjust_end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n, String end_time, int adjust) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_3(symbols, frequency, n, end_time, adjust);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n, String end_time) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_4(symbols, frequency, n, end_time);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_Bar_t history_bars_n(String symbols, String frequency, int n) {
    long cPtr = gmsdkJNI.history_bars_n__SWIG_5(symbols, frequency, n);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_Bar_t(cPtr, false);
  }

  public static DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter, String order_by, int limit) {
    long cPtr = gmsdkJNI.get_fundamentals__SWIG_0(table, symbols, start_date, end_date, fields, filter, order_by, limit);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter, String order_by) {
    long cPtr = gmsdkJNI.get_fundamentals__SWIG_1(table, symbols, start_date, end_date, fields, filter, order_by);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields, String filter) {
    long cPtr = gmsdkJNI.get_fundamentals__SWIG_2(table, symbols, start_date, end_date, fields, filter);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals(String table, String symbols, String start_date, String end_date, String fields) {
    long cPtr = gmsdkJNI.get_fundamentals__SWIG_3(table, symbols, start_date, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n, String filter, String order_by) {
    long cPtr = gmsdkJNI.get_fundamentals_n__SWIG_0(table, symbols, end_date, fields, n, filter, order_by);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n, String filter) {
    long cPtr = gmsdkJNI.get_fundamentals_n__SWIG_1(table, symbols, end_date, fields, n, filter);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields, int n) {
    long cPtr = gmsdkJNI.get_fundamentals_n__SWIG_2(table, symbols, end_date, fields, n);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_fundamentals_n(String table, String symbols, String end_date, String fields) {
    long cPtr = gmsdkJNI.get_fundamentals_n__SWIG_3(table, symbols, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instruments(String exchanges, String sec_types, String fields) {
    long cPtr = gmsdkJNI.get_instruments__SWIG_0(exchanges, sec_types, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instruments(String exchanges, String sec_types) {
    long cPtr = gmsdkJNI.get_instruments__SWIG_1(exchanges, sec_types);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instruments(String exchanges) {
    long cPtr = gmsdkJNI.get_instruments__SWIG_2(exchanges);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instruments() {
    long cPtr = gmsdkJNI.get_instruments__SWIG_3();
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_history_instruments(String symbols, String start_date, String end_date, String fields) {
    long cPtr = gmsdkJNI.get_history_instruments__SWIG_0(symbols, start_date, end_date, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_history_instruments(String symbols, String start_date, String end_date) {
    long cPtr = gmsdkJNI.get_history_instruments__SWIG_1(symbols, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types, String names, String fields) {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_0(symbols, exchanges, sec_types, names, fields);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types, String names) {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_1(symbols, exchanges, sec_types, names);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos(String symbols, String exchanges, String sec_types) {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_2(symbols, exchanges, sec_types);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos(String symbols, String exchanges) {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_3(symbols, exchanges);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos(String symbols) {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_4(symbols);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_instrumentinfos() {
    long cPtr = gmsdkJNI.get_instrumentinfos__SWIG_5();
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_constituents(String index, String trade_date) {
    long cPtr = gmsdkJNI.get_constituents__SWIG_0(index, trade_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_constituents(String index) {
    long cPtr = gmsdkJNI.get_constituents__SWIG_1(index);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_char_aLEN_SYMBOLA_t get_industry(String code) {
    long cPtr = gmsdkJNI.get_industry(code);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_char_aLEN_SYMBOLA_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_char_aLEN_SYMBOLA_t get_concept(String code) {
    long cPtr = gmsdkJNI.get_concept(code);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_char_aLEN_SYMBOLA_t(cPtr, false);
  }

  public static SWIGTYPE_p_DataArrayT_char_aLEN_ISO_DATATIMEA_t get_trading_dates(String exchange, String start_date, String end_date) {
    long cPtr = gmsdkJNI.get_trading_dates(exchange, start_date, end_date);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataArrayT_char_aLEN_ISO_DATATIMEA_t(cPtr, false);
  }

  public static int get_previous_trading_date(String exchange, String date, String output_date) {
    return gmsdkJNI.get_previous_trading_date(exchange, date, output_date);
  }

  public static int get_next_trading_date(String exchange, String date, String output_date) {
    return gmsdkJNI.get_next_trading_date(exchange, date, output_date);
  }

  public static DataSet get_dividend(String symbol, String start_date, String end_date) {
    long cPtr = gmsdkJNI.get_dividend(symbol, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static DataSet get_continuous_contracts(String csymbol, String start_date, String end_date) {
    long cPtr = gmsdkJNI.get_continuous_contracts(csymbol, start_date, end_date);
    return (cPtr == 0) ? null : new DataSet(cPtr, false);
  }

  public static long getLEN_ID() {
    return gmsdkJNI.LEN_ID_get();
  }

  public static long getLEN_NAME() {
    return gmsdkJNI.LEN_NAME_get();
  }

  public static long getLEN_SYMBOL() {
    return gmsdkJNI.LEN_SYMBOL_get();
  }

  public static long getLEN_INFO() {
    return gmsdkJNI.LEN_INFO_get();
  }

  public static long getLEN_EXCHANGE() {
    return gmsdkJNI.LEN_EXCHANGE_get();
  }

  public static long getLEN_ISO_DATATIME() {
    return gmsdkJNI.LEN_ISO_DATATIME_get();
  }

  public static long getLEN_FREQUENCY() {
    return gmsdkJNI.LEN_FREQUENCY_get();
  }

  public static long getDEPTH_OF_QUOTE() {
    return gmsdkJNI.DEPTH_OF_QUOTE_get();
  }

}
