/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public interface gmsdkConstants {
  public final static int SUCCESS = gmsdkJNI.SUCCESS_get();
  public final static int ERR_INVALID_TOKEN = gmsdkJNI.ERR_INVALID_TOKEN_get();
  public final static int ERR_CONNECT_TERM_SERV = gmsdkJNI.ERR_CONNECT_TERM_SERV_get();
  public final static int ERR_CONNECT_HISTORY_SERV = gmsdkJNI.ERR_CONNECT_HISTORY_SERV_get();
  public final static int ERR_QUERY_SERVER_ADDR_ERROR = gmsdkJNI.ERR_QUERY_SERVER_ADDR_ERROR_get();
  public final static int ERR_PARSE_MASSAGE = gmsdkJNI.ERR_PARSE_MASSAGE_get();
  public final static int ERR_PARSE_NETWORK_MASSAGE = gmsdkJNI.ERR_PARSE_NETWORK_MASSAGE_get();
  public final static int ERR_CALL_TRADE_SERVICE = gmsdkJNI.ERR_CALL_TRADE_SERVICE_get();
  public final static int ERR_CALL_HISTORY_SERVICE = gmsdkJNI.ERR_CALL_HISTORY_SERVICE_get();
  public final static int ERR_CALL_STRATEGY_SERIVCE = gmsdkJNI.ERR_CALL_STRATEGY_SERIVCE_get();
  public final static int ERR_CALL_RTCONFIG_SERIVCE = gmsdkJNI.ERR_CALL_RTCONFIG_SERIVCE_get();
  public final static int ERR_CALL_FUNDMENTAL_SERVICE = gmsdkJNI.ERR_CALL_FUNDMENTAL_SERVICE_get();
  public final static int ERR_CALL_BACKTEST_SERVICE = gmsdkJNI.ERR_CALL_BACKTEST_SERVICE_get();
  public final static int ERR_CALL_TRADEGW_SERIVCE = gmsdkJNI.ERR_CALL_TRADEGW_SERIVCE_get();
  public final static int ERR_INVALID_ACCOUNT_ID = gmsdkJNI.ERR_INVALID_ACCOUNT_ID_get();
  public final static int ERR_INVALID_DATE = gmsdkJNI.ERR_INVALID_DATE_get();
  public final static int ERR_TD_LIVE_CONNECT = gmsdkJNI.ERR_TD_LIVE_CONNECT_get();
  public final static int ERR_TD_LIVE_CONNECT_LOST = gmsdkJNI.ERR_TD_LIVE_CONNECT_LOST_get();
  public final static int ERR_MD_LIVE_CONNECT = gmsdkJNI.ERR_MD_LIVE_CONNECT_get();
  public final static int ERR_MD_LIVE_CONNECT_LOST = gmsdkJNI.ERR_MD_LIVE_CONNECT_LOST_get();
  public final static int ERR_BT_BEGIN = gmsdkJNI.ERR_BT_BEGIN_get();
  public final static int ERR_BT_INVALID_TIMESPAN = gmsdkJNI.ERR_BT_INVALID_TIMESPAN_get();
  public final static int ERR_BT_READ_CACHE_ERROR = gmsdkJNI.ERR_BT_READ_CACHE_ERROR_get();
  public final static int ERR_BT_WRITE_CACHE_ERROR = gmsdkJNI.ERR_BT_WRITE_CACHE_ERROR_get();
}
