/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public class Indicator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Indicator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Indicator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_Indicator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccount_id(String value) {
    gmsdkJNI.Indicator_account_id_set(swigCPtr, this, value);
  }

  public String getAccount_id() {
    return gmsdkJNI.Indicator_account_id_get(swigCPtr, this);
  }

  public void setPnl_ratio(double value) {
    gmsdkJNI.Indicator_pnl_ratio_set(swigCPtr, this, value);
  }

  public double getPnl_ratio() {
    return gmsdkJNI.Indicator_pnl_ratio_get(swigCPtr, this);
  }

  public void setPnl_ratio_annual(double value) {
    gmsdkJNI.Indicator_pnl_ratio_annual_set(swigCPtr, this, value);
  }

  public double getPnl_ratio_annual() {
    return gmsdkJNI.Indicator_pnl_ratio_annual_get(swigCPtr, this);
  }

  public void setSharp_ratio(double value) {
    gmsdkJNI.Indicator_sharp_ratio_set(swigCPtr, this, value);
  }

  public double getSharp_ratio() {
    return gmsdkJNI.Indicator_sharp_ratio_get(swigCPtr, this);
  }

  public void setMax_drawdown(double value) {
    gmsdkJNI.Indicator_max_drawdown_set(swigCPtr, this, value);
  }

  public double getMax_drawdown() {
    return gmsdkJNI.Indicator_max_drawdown_get(swigCPtr, this);
  }

  public void setRisk_ratio(double value) {
    gmsdkJNI.Indicator_risk_ratio_set(swigCPtr, this, value);
  }

  public double getRisk_ratio() {
    return gmsdkJNI.Indicator_risk_ratio_get(swigCPtr, this);
  }

  public void setOpen_count(int value) {
    gmsdkJNI.Indicator_open_count_set(swigCPtr, this, value);
  }

  public int getOpen_count() {
    return gmsdkJNI.Indicator_open_count_get(swigCPtr, this);
  }

  public void setClose_count(int value) {
    gmsdkJNI.Indicator_close_count_set(swigCPtr, this, value);
  }

  public int getClose_count() {
    return gmsdkJNI.Indicator_close_count_get(swigCPtr, this);
  }

  public void setWin_count(int value) {
    gmsdkJNI.Indicator_win_count_set(swigCPtr, this, value);
  }

  public int getWin_count() {
    return gmsdkJNI.Indicator_win_count_get(swigCPtr, this);
  }

  public void setLose_count(int value) {
    gmsdkJNI.Indicator_lose_count_set(swigCPtr, this, value);
  }

  public int getLose_count() {
    return gmsdkJNI.Indicator_lose_count_get(swigCPtr, this);
  }

  public void setWin_ratio(double value) {
    gmsdkJNI.Indicator_win_ratio_set(swigCPtr, this, value);
  }

  public double getWin_ratio() {
    return gmsdkJNI.Indicator_win_ratio_get(swigCPtr, this);
  }

  public void setCreated_at(long value) {
    gmsdkJNI.Indicator_created_at_set(swigCPtr, this, value);
  }

  public long getCreated_at() {
    return gmsdkJNI.Indicator_created_at_get(swigCPtr, this);
  }

  public void setUpdated_at(long value) {
    gmsdkJNI.Indicator_updated_at_set(swigCPtr, this, value);
  }

  public long getUpdated_at() {
    return gmsdkJNI.Indicator_updated_at_get(swigCPtr, this);
  }

  public Indicator() {
    this(gmsdkJNI.new_Indicator(), true);
  }

}
