/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class OrderType {
  public final static OrderType OrderType_Unknown = new OrderType("OrderType_Unknown", gmsdkJNI.OrderType_Unknown_get());
  public final static OrderType OrderType_Limit = new OrderType("OrderType_Limit", gmsdkJNI.OrderType_Limit_get());
  public final static OrderType OrderType_Market = new OrderType("OrderType_Market", gmsdkJNI.OrderType_Market_get());
  public final static OrderType OrderType_Stop = new OrderType("OrderType_Stop", gmsdkJNI.OrderType_Stop_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderType.class + " with value " + swigValue);
  }

  private OrderType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderType(String swigName, OrderType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderType[] swigValues = { OrderType_Unknown, OrderType_Limit, OrderType_Market, OrderType_Stop };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

