/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class OrderSide {
  public final static OrderSide OrderSide_Unknown = new OrderSide("OrderSide_Unknown", gmsdkJNI.OrderSide_Unknown_get());
  public final static OrderSide OrderSide_Buy = new OrderSide("OrderSide_Buy", gmsdkJNI.OrderSide_Buy_get());
  public final static OrderSide OrderSide_Sell = new OrderSide("OrderSide_Sell", gmsdkJNI.OrderSide_Sell_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderSide swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderSide.class + " with value " + swigValue);
  }

  private OrderSide(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderSide(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderSide(String swigName, OrderSide swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderSide[] swigValues = { OrderSide_Unknown, OrderSide_Buy, OrderSide_Sell };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

