/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public class Order {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Order(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Order obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_Order(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStrategy_id(String value) {
    gmsdkJNI.Order_strategy_id_set(swigCPtr, this, value);
  }

  public String getStrategy_id() {
    return gmsdkJNI.Order_strategy_id_get(swigCPtr, this);
  }

  public void setAccount_id(String value) {
    gmsdkJNI.Order_account_id_set(swigCPtr, this, value);
  }

  public String getAccount_id() {
    return gmsdkJNI.Order_account_id_get(swigCPtr, this);
  }

  public void setAccount_name(String value) {
    gmsdkJNI.Order_account_name_set(swigCPtr, this, value);
  }

  public String getAccount_name() {
    return gmsdkJNI.Order_account_name_get(swigCPtr, this);
  }

  public void setCl_ord_id(String value) {
    gmsdkJNI.Order_cl_ord_id_set(swigCPtr, this, value);
  }

  public String getCl_ord_id() {
    return gmsdkJNI.Order_cl_ord_id_get(swigCPtr, this);
  }

  public void setOrder_id(String value) {
    gmsdkJNI.Order_order_id_set(swigCPtr, this, value);
  }

  public String getOrder_id() {
    return gmsdkJNI.Order_order_id_get(swigCPtr, this);
  }

  public void setEx_ord_id(String value) {
    gmsdkJNI.Order_ex_ord_id_set(swigCPtr, this, value);
  }

  public String getEx_ord_id() {
    return gmsdkJNI.Order_ex_ord_id_get(swigCPtr, this);
  }

  public void setSymbol(String value) {
    gmsdkJNI.Order_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return gmsdkJNI.Order_symbol_get(swigCPtr, this);
  }

  public void setSide(int value) {
    gmsdkJNI.Order_side_set(swigCPtr, this, value);
  }

  public int getSide() {
    return gmsdkJNI.Order_side_get(swigCPtr, this);
  }

  public void setPosition_effect(int value) {
    gmsdkJNI.Order_position_effect_set(swigCPtr, this, value);
  }

  public int getPosition_effect() {
    return gmsdkJNI.Order_position_effect_get(swigCPtr, this);
  }

  public void setPosition_side(int value) {
    gmsdkJNI.Order_position_side_set(swigCPtr, this, value);
  }

  public int getPosition_side() {
    return gmsdkJNI.Order_position_side_get(swigCPtr, this);
  }

  public void setOrder_type(int value) {
    gmsdkJNI.Order_order_type_set(swigCPtr, this, value);
  }

  public int getOrder_type() {
    return gmsdkJNI.Order_order_type_get(swigCPtr, this);
  }

  public void setOrder_duration(int value) {
    gmsdkJNI.Order_order_duration_set(swigCPtr, this, value);
  }

  public int getOrder_duration() {
    return gmsdkJNI.Order_order_duration_get(swigCPtr, this);
  }

  public void setOrder_qualifier(int value) {
    gmsdkJNI.Order_order_qualifier_set(swigCPtr, this, value);
  }

  public int getOrder_qualifier() {
    return gmsdkJNI.Order_order_qualifier_get(swigCPtr, this);
  }

  public void setOrder_src(int value) {
    gmsdkJNI.Order_order_src_set(swigCPtr, this, value);
  }

  public int getOrder_src() {
    return gmsdkJNI.Order_order_src_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    gmsdkJNI.Order_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return gmsdkJNI.Order_status_get(swigCPtr, this);
  }

  public void setOrd_rej_reason(int value) {
    gmsdkJNI.Order_ord_rej_reason_set(swigCPtr, this, value);
  }

  public int getOrd_rej_reason() {
    return gmsdkJNI.Order_ord_rej_reason_get(swigCPtr, this);
  }

  public void setOrd_rej_reason_detail(String value) {
    gmsdkJNI.Order_ord_rej_reason_detail_set(swigCPtr, this, value);
  }

  public String getOrd_rej_reason_detail() {
    return gmsdkJNI.Order_ord_rej_reason_detail_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    gmsdkJNI.Order_price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return gmsdkJNI.Order_price_get(swigCPtr, this);
  }

  public void setStop_price(double value) {
    gmsdkJNI.Order_stop_price_set(swigCPtr, this, value);
  }

  public double getStop_price() {
    return gmsdkJNI.Order_stop_price_get(swigCPtr, this);
  }

  public void setOrder_style(int value) {
    gmsdkJNI.Order_order_style_set(swigCPtr, this, value);
  }

  public int getOrder_style() {
    return gmsdkJNI.Order_order_style_get(swigCPtr, this);
  }

  public void setVolume(long value) {
    gmsdkJNI.Order_volume_set(swigCPtr, this, value);
  }

  public long getVolume() {
    return gmsdkJNI.Order_volume_get(swigCPtr, this);
  }

  public void setValue(double value) {
    gmsdkJNI.Order_value_set(swigCPtr, this, value);
  }

  public double getValue() {
    return gmsdkJNI.Order_value_get(swigCPtr, this);
  }

  public void setPercent(double value) {
    gmsdkJNI.Order_percent_set(swigCPtr, this, value);
  }

  public double getPercent() {
    return gmsdkJNI.Order_percent_get(swigCPtr, this);
  }

  public void setTarget_volume(long value) {
    gmsdkJNI.Order_target_volume_set(swigCPtr, this, value);
  }

  public long getTarget_volume() {
    return gmsdkJNI.Order_target_volume_get(swigCPtr, this);
  }

  public void setTarget_value(double value) {
    gmsdkJNI.Order_target_value_set(swigCPtr, this, value);
  }

  public double getTarget_value() {
    return gmsdkJNI.Order_target_value_get(swigCPtr, this);
  }

  public void setTarget_percent(double value) {
    gmsdkJNI.Order_target_percent_set(swigCPtr, this, value);
  }

  public double getTarget_percent() {
    return gmsdkJNI.Order_target_percent_get(swigCPtr, this);
  }

  public void setFilled_volume(long value) {
    gmsdkJNI.Order_filled_volume_set(swigCPtr, this, value);
  }

  public long getFilled_volume() {
    return gmsdkJNI.Order_filled_volume_get(swigCPtr, this);
  }

  public void setFilled_vwap(double value) {
    gmsdkJNI.Order_filled_vwap_set(swigCPtr, this, value);
  }

  public double getFilled_vwap() {
    return gmsdkJNI.Order_filled_vwap_get(swigCPtr, this);
  }

  public void setFilled_amount(double value) {
    gmsdkJNI.Order_filled_amount_set(swigCPtr, this, value);
  }

  public double getFilled_amount() {
    return gmsdkJNI.Order_filled_amount_get(swigCPtr, this);
  }

  public void setFilled_commission(double value) {
    gmsdkJNI.Order_filled_commission_set(swigCPtr, this, value);
  }

  public double getFilled_commission() {
    return gmsdkJNI.Order_filled_commission_get(swigCPtr, this);
  }

  public void setCreated_at(long value) {
    gmsdkJNI.Order_created_at_set(swigCPtr, this, value);
  }

  public long getCreated_at() {
    return gmsdkJNI.Order_created_at_get(swigCPtr, this);
  }

  public void setUpdated_at(long value) {
    gmsdkJNI.Order_updated_at_set(swigCPtr, this, value);
  }

  public long getUpdated_at() {
    return gmsdkJNI.Order_updated_at_get(swigCPtr, this);
  }

  public Order() {
    this(gmsdkJNI.new_Order(), true);
  }

}
