/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm;

public class OrderDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OrderDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OrderDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_OrderDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmsdkJNI.OrderDataArray_status(swigCPtr, this);
  }

  public Order data() {
    long cPtr = gmsdkJNI.OrderDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new Order(cPtr, false);
  }

  public int count() {
    return gmsdkJNI.OrderDataArray_count(swigCPtr, this);
  }

  public Order at(int i) {
    return new Order(gmsdkJNI.OrderDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmsdkJNI.OrderDataArray_release(swigCPtr, this);
  }

}
