/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class OrderDuration {
  public final static OrderDuration OrderDuration_Unknown = new OrderDuration("OrderDuration_Unknown", gmsdkJNI.OrderDuration_Unknown_get());
  public final static OrderDuration OrderDuration_FAK = new OrderDuration("OrderDuration_FAK", gmsdkJNI.OrderDuration_FAK_get());
  public final static OrderDuration OrderDuration_FOK = new OrderDuration("OrderDuration_FOK", gmsdkJNI.OrderDuration_FOK_get());
  public final static OrderDuration OrderDuration_GFD = new OrderDuration("OrderDuration_GFD", gmsdkJNI.OrderDuration_GFD_get());
  public final static OrderDuration OrderDuration_GFS = new OrderDuration("OrderDuration_GFS", gmsdkJNI.OrderDuration_GFS_get());
  public final static OrderDuration OrderDuration_GTD = new OrderDuration("OrderDuration_GTD", gmsdkJNI.OrderDuration_GTD_get());
  public final static OrderDuration OrderDuration_GTC = new OrderDuration("OrderDuration_GTC", gmsdkJNI.OrderDuration_GTC_get());
  public final static OrderDuration OrderDuration_GFA = new OrderDuration("OrderDuration_GFA", gmsdkJNI.OrderDuration_GFA_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderDuration swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderDuration.class + " with value " + swigValue);
  }

  private OrderDuration(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderDuration(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderDuration(String swigName, OrderDuration swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderDuration[] swigValues = { OrderDuration_Unknown, OrderDuration_FAK, OrderDuration_FOK, OrderDuration_GFD, OrderDuration_GFS, OrderDuration_GTD, OrderDuration_GTC, OrderDuration_GFA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

