/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class OrderQualifier {
  public final static OrderQualifier OrderQualifier_Unknown = new OrderQualifier("OrderQualifier_Unknown", gmsdkJNI.OrderQualifier_Unknown_get());
  public final static OrderQualifier OrderQualifier_BOC = new OrderQualifier("OrderQualifier_BOC", gmsdkJNI.OrderQualifier_BOC_get());
  public final static OrderQualifier OrderQualifier_BOP = new OrderQualifier("OrderQualifier_BOP", gmsdkJNI.OrderQualifier_BOP_get());
  public final static OrderQualifier OrderQualifier_B5TC = new OrderQualifier("OrderQualifier_B5TC", gmsdkJNI.OrderQualifier_B5TC_get());
  public final static OrderQualifier OrderQualifier_B5TL = new OrderQualifier("OrderQualifier_B5TL", gmsdkJNI.OrderQualifier_B5TL_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderQualifier swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderQualifier.class + " with value " + swigValue);
  }

  private OrderQualifier(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderQualifier(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderQualifier(String swigName, OrderQualifier swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderQualifier[] swigValues = { OrderQualifier_Unknown, OrderQualifier_BOC, OrderQualifier_BOP, OrderQualifier_B5TC, OrderQualifier_B5TL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

