/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class OrderRejectReason {
  public final static OrderRejectReason OrderRejectReason_Unknown = new OrderRejectReason("OrderRejectReason_Unknown", gmsdkJNI.OrderRejectReason_Unknown_get());
  public final static OrderRejectReason OrderRejectReason_RiskRuleCheckFailed = new OrderRejectReason("OrderRejectReason_RiskRuleCheckFailed", gmsdkJNI.OrderRejectReason_RiskRuleCheckFailed_get());
  public final static OrderRejectReason OrderRejectReason_NoEnoughCash = new OrderRejectReason("OrderRejectReason_NoEnoughCash", gmsdkJNI.OrderRejectReason_NoEnoughCash_get());
  public final static OrderRejectReason OrderRejectReason_NoEnoughPosition = new OrderRejectReason("OrderRejectReason_NoEnoughPosition", gmsdkJNI.OrderRejectReason_NoEnoughPosition_get());
  public final static OrderRejectReason OrderRejectReason_IllegalAccountId = new OrderRejectReason("OrderRejectReason_IllegalAccountId", gmsdkJNI.OrderRejectReason_IllegalAccountId_get());
  public final static OrderRejectReason OrderRejectReason_IllegalStrategyId = new OrderRejectReason("OrderRejectReason_IllegalStrategyId", gmsdkJNI.OrderRejectReason_IllegalStrategyId_get());
  public final static OrderRejectReason OrderRejectReason_IllegalSymbol = new OrderRejectReason("OrderRejectReason_IllegalSymbol", gmsdkJNI.OrderRejectReason_IllegalSymbol_get());
  public final static OrderRejectReason OrderRejectReason_IllegalVolume = new OrderRejectReason("OrderRejectReason_IllegalVolume", gmsdkJNI.OrderRejectReason_IllegalVolume_get());
  public final static OrderRejectReason OrderRejectReason_IllegalPrice = new OrderRejectReason("OrderRejectReason_IllegalPrice", gmsdkJNI.OrderRejectReason_IllegalPrice_get());
  public final static OrderRejectReason OrderRejectReason_AccountDisabled = new OrderRejectReason("OrderRejectReason_AccountDisabled", gmsdkJNI.OrderRejectReason_AccountDisabled_get());
  public final static OrderRejectReason OrderRejectReason_AccountDisconnected = new OrderRejectReason("OrderRejectReason_AccountDisconnected", gmsdkJNI.OrderRejectReason_AccountDisconnected_get());
  public final static OrderRejectReason OrderRejectReason_AccountLoggedout = new OrderRejectReason("OrderRejectReason_AccountLoggedout", gmsdkJNI.OrderRejectReason_AccountLoggedout_get());
  public final static OrderRejectReason OrderRejectReason_NotInTradingSession = new OrderRejectReason("OrderRejectReason_NotInTradingSession", gmsdkJNI.OrderRejectReason_NotInTradingSession_get());
  public final static OrderRejectReason OrderRejectReason_OrderTypeNotSupported = new OrderRejectReason("OrderRejectReason_OrderTypeNotSupported", gmsdkJNI.OrderRejectReason_OrderTypeNotSupported_get());
  public final static OrderRejectReason OrderRejectReason_Throttle = new OrderRejectReason("OrderRejectReason_Throttle", gmsdkJNI.OrderRejectReason_Throttle_get());
  public final static OrderRejectReason OrderRejectReason_SymbolSusppended = new OrderRejectReason("OrderRejectReason_SymbolSusppended", gmsdkJNI.OrderRejectReason_SymbolSusppended_get());
  public final static OrderRejectReason OrderRejectReason_Internal = new OrderRejectReason("OrderRejectReason_Internal", gmsdkJNI.OrderRejectReason_Internal_get());
  public final static OrderRejectReason CancelOrderRejectReason_OrderFinalized = new OrderRejectReason("CancelOrderRejectReason_OrderFinalized", gmsdkJNI.CancelOrderRejectReason_OrderFinalized_get());
  public final static OrderRejectReason CancelOrderRejectReason_UnknownOrder = new OrderRejectReason("CancelOrderRejectReason_UnknownOrder", gmsdkJNI.CancelOrderRejectReason_UnknownOrder_get());
  public final static OrderRejectReason CancelOrderRejectReason_BrokerOption = new OrderRejectReason("CancelOrderRejectReason_BrokerOption", gmsdkJNI.CancelOrderRejectReason_BrokerOption_get());
  public final static OrderRejectReason CancelOrderRejectReason_AlreadyInPendingCancel = new OrderRejectReason("CancelOrderRejectReason_AlreadyInPendingCancel", gmsdkJNI.CancelOrderRejectReason_AlreadyInPendingCancel_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OrderRejectReason swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OrderRejectReason.class + " with value " + swigValue);
  }

  private OrderRejectReason(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OrderRejectReason(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OrderRejectReason(String swigName, OrderRejectReason swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OrderRejectReason[] swigValues = { OrderRejectReason_Unknown, OrderRejectReason_RiskRuleCheckFailed, OrderRejectReason_NoEnoughCash, OrderRejectReason_NoEnoughPosition, OrderRejectReason_IllegalAccountId, OrderRejectReason_IllegalStrategyId, OrderRejectReason_IllegalSymbol, OrderRejectReason_IllegalVolume, OrderRejectReason_IllegalPrice, OrderRejectReason_AccountDisabled, OrderRejectReason_AccountDisconnected, OrderRejectReason_AccountLoggedout, OrderRejectReason_NotInTradingSession, OrderRejectReason_OrderTypeNotSupported, OrderRejectReason_Throttle, OrderRejectReason_SymbolSusppended, OrderRejectReason_Internal, CancelOrderRejectReason_OrderFinalized, CancelOrderRejectReason_UnknownOrder, CancelOrderRejectReason_BrokerOption, CancelOrderRejectReason_AlreadyInPendingCancel };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

