/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public class Parameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Parameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Parameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_Parameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(String value) {
    gmsdkJNI.Parameter_key_set(swigCPtr, this, value);
  }

  public String getKey() {
    return gmsdkJNI.Parameter_key_get(swigCPtr, this);
  }

  public void setValue(double value) {
    gmsdkJNI.Parameter_value_set(swigCPtr, this, value);
  }

  public double getValue() {
    return gmsdkJNI.Parameter_value_get(swigCPtr, this);
  }

  public void setMin(double value) {
    gmsdkJNI.Parameter_min_set(swigCPtr, this, value);
  }

  public double getMin() {
    return gmsdkJNI.Parameter_min_get(swigCPtr, this);
  }

  public void setMax(double value) {
    gmsdkJNI.Parameter_max_set(swigCPtr, this, value);
  }

  public double getMax() {
    return gmsdkJNI.Parameter_max_get(swigCPtr, this);
  }

  public void setName(String value) {
    gmsdkJNI.Parameter_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return gmsdkJNI.Parameter_name_get(swigCPtr, this);
  }

  public void setIntro(String value) {
    gmsdkJNI.Parameter_intro_set(swigCPtr, this, value);
  }

  public String getIntro() {
    return gmsdkJNI.Parameter_intro_get(swigCPtr, this);
  }

  public void setGroup(String value) {
    gmsdkJNI.Parameter_group_set(swigCPtr, this, value);
  }

  public String getGroup() {
    return gmsdkJNI.Parameter_group_get(swigCPtr, this);
  }

  public void setReadonly(boolean value) {
    gmsdkJNI.Parameter_readonly_set(swigCPtr, this, value);
  }

  public boolean getReadonly() {
    return gmsdkJNI.Parameter_readonly_get(swigCPtr, this);
  }

  public Parameter() {
    this(gmsdkJNI.new_Parameter(), true);
  }

}
