/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm;

public class ParameterDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParameterDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParameterDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmsdkJNI.delete_ParameterDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmsdkJNI.ParameterDataArray_status(swigCPtr, this);
  }

  public Parameter data() {
    long cPtr = gmsdkJNI.ParameterDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new Parameter(cPtr, false);
  }

  public int count() {
    return gmsdkJNI.ParameterDataArray_count(swigCPtr, this);
  }

  public Parameter at(int i) {
    return new Parameter(gmsdkJNI.ParameterDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmsdkJNI.ParameterDataArray_release(swigCPtr, this);
  }

}
