/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.skywalker.gmsdk;

public final class PositionEffect {
  public final static PositionEffect PositionEffect_Unknown = new PositionEffect("PositionEffect_Unknown", gmsdkJNI.PositionEffect_Unknown_get());
  public final static PositionEffect PositionEffect_Open = new PositionEffect("PositionEffect_Open", gmsdkJNI.PositionEffect_Open_get());
  public final static PositionEffect PositionEffect_Close = new PositionEffect("PositionEffect_Close", gmsdkJNI.PositionEffect_Close_get());
  public final static PositionEffect PositionEffect_CloseToday = new PositionEffect("PositionEffect_CloseToday", gmsdkJNI.PositionEffect_CloseToday_get());
  public final static PositionEffect PositionEffect_CloseYesterday = new PositionEffect("PositionEffect_CloseYesterday", gmsdkJNI.PositionEffect_CloseYesterday_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static PositionEffect swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + PositionEffect.class + " with value " + swigValue);
  }

  private PositionEffect(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private PositionEffect(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private PositionEffect(String swigName, PositionEffect swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static PositionEffect[] swigValues = { PositionEffect_Unknown, PositionEffect_Open, PositionEffect_Close, PositionEffect_CloseToday, PositionEffect_CloseYesterday };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

