/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.td;

public class AccountStatusDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AccountStatusDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccountStatusDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmtradeJNI.delete_AccountStatusDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmtradeJNI.AccountStatusDataArray_status(swigCPtr, this);
  }

  public AccountStatus data() {
    long cPtr = gmtradeJNI.AccountStatusDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new AccountStatus(cPtr, false);
  }

  public int count() {
    return gmtradeJNI.AccountStatusDataArray_count(swigCPtr, this);
  }

  public AccountStatus at(int i) {
    return new AccountStatus(gmtradeJNI.AccountStatusDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmtradeJNI.AccountStatusDataArray_release(swigCPtr, this);
  }

}
