/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.td;

public class Cash {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Cash(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Cash obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmtradeJNI.delete_Cash(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccount_id(String value) {
    gmtradeJNI.Cash_account_id_set(swigCPtr, this, value);
  }

  public String getAccount_id() {
    return gmtradeJNI.Cash_account_id_get(swigCPtr, this);
  }

  public void setAccount_name(String value) {
    gmtradeJNI.Cash_account_name_set(swigCPtr, this, value);
  }

  public String getAccount_name() {
    return gmtradeJNI.Cash_account_name_get(swigCPtr, this);
  }

  public void setCurrency(int value) {
    gmtradeJNI.Cash_currency_set(swigCPtr, this, value);
  }

  public int getCurrency() {
    return gmtradeJNI.Cash_currency_get(swigCPtr, this);
  }

  public void setNav(double value) {
    gmtradeJNI.Cash_nav_set(swigCPtr, this, value);
  }

  public double getNav() {
    return gmtradeJNI.Cash_nav_get(swigCPtr, this);
  }

  public void setPnl(double value) {
    gmtradeJNI.Cash_pnl_set(swigCPtr, this, value);
  }

  public double getPnl() {
    return gmtradeJNI.Cash_pnl_get(swigCPtr, this);
  }

  public void setFpnl(double value) {
    gmtradeJNI.Cash_fpnl_set(swigCPtr, this, value);
  }

  public double getFpnl() {
    return gmtradeJNI.Cash_fpnl_get(swigCPtr, this);
  }

  public void setFrozen(double value) {
    gmtradeJNI.Cash_frozen_set(swigCPtr, this, value);
  }

  public double getFrozen() {
    return gmtradeJNI.Cash_frozen_get(swigCPtr, this);
  }

  public void setOrder_frozen(double value) {
    gmtradeJNI.Cash_order_frozen_set(swigCPtr, this, value);
  }

  public double getOrder_frozen() {
    return gmtradeJNI.Cash_order_frozen_get(swigCPtr, this);
  }

  public void setAvailable(double value) {
    gmtradeJNI.Cash_available_set(swigCPtr, this, value);
  }

  public double getAvailable() {
    return gmtradeJNI.Cash_available_get(swigCPtr, this);
  }

  public void setBalance(double value) {
    gmtradeJNI.Cash_balance_set(swigCPtr, this, value);
  }

  public double getBalance() {
    return gmtradeJNI.Cash_balance_get(swigCPtr, this);
  }

  public void setCum_inout(double value) {
    gmtradeJNI.Cash_cum_inout_set(swigCPtr, this, value);
  }

  public double getCum_inout() {
    return gmtradeJNI.Cash_cum_inout_get(swigCPtr, this);
  }

  public void setCum_trade(double value) {
    gmtradeJNI.Cash_cum_trade_set(swigCPtr, this, value);
  }

  public double getCum_trade() {
    return gmtradeJNI.Cash_cum_trade_get(swigCPtr, this);
  }

  public void setCum_pnl(double value) {
    gmtradeJNI.Cash_cum_pnl_set(swigCPtr, this, value);
  }

  public double getCum_pnl() {
    return gmtradeJNI.Cash_cum_pnl_get(swigCPtr, this);
  }

  public void setCum_commission(double value) {
    gmtradeJNI.Cash_cum_commission_set(swigCPtr, this, value);
  }

  public double getCum_commission() {
    return gmtradeJNI.Cash_cum_commission_get(swigCPtr, this);
  }

  public void setLast_trade(double value) {
    gmtradeJNI.Cash_last_trade_set(swigCPtr, this, value);
  }

  public double getLast_trade() {
    return gmtradeJNI.Cash_last_trade_get(swigCPtr, this);
  }

  public void setLast_pnl(double value) {
    gmtradeJNI.Cash_last_pnl_set(swigCPtr, this, value);
  }

  public double getLast_pnl() {
    return gmtradeJNI.Cash_last_pnl_get(swigCPtr, this);
  }

  public void setLast_commission(double value) {
    gmtradeJNI.Cash_last_commission_set(swigCPtr, this, value);
  }

  public double getLast_commission() {
    return gmtradeJNI.Cash_last_commission_get(swigCPtr, this);
  }

  public void setLast_inout(double value) {
    gmtradeJNI.Cash_last_inout_set(swigCPtr, this, value);
  }

  public double getLast_inout() {
    return gmtradeJNI.Cash_last_inout_get(swigCPtr, this);
  }

  public void setChange_reason(int value) {
    gmtradeJNI.Cash_change_reason_set(swigCPtr, this, value);
  }

  public int getChange_reason() {
    return gmtradeJNI.Cash_change_reason_get(swigCPtr, this);
  }

  public void setChange_event_id(String value) {
    gmtradeJNI.Cash_change_event_id_set(swigCPtr, this, value);
  }

  public String getChange_event_id() {
    return gmtradeJNI.Cash_change_event_id_get(swigCPtr, this);
  }

  public void setCreated_at(long value) {
    gmtradeJNI.Cash_created_at_set(swigCPtr, this, value);
  }

  public long getCreated_at() {
    return gmtradeJNI.Cash_created_at_get(swigCPtr, this);
  }

  public void setUpdated_at(long value) {
    gmtradeJNI.Cash_updated_at_set(swigCPtr, this, value);
  }

  public long getUpdated_at() {
    return gmtradeJNI.Cash_updated_at_get(swigCPtr, this);
  }

  public Cash() {
    this(gmtradeJNI.new_Cash(), true);
  }

}
