/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.td;

public class ExecRptDataArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ExecRptDataArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExecRptDataArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmtradeJNI.delete_ExecRptDataArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int status() {
    return gmtradeJNI.ExecRptDataArray_status(swigCPtr, this);
  }

  public ExecRpt data() {
    long cPtr = gmtradeJNI.ExecRptDataArray_data(swigCPtr, this);
    return (cPtr == 0) ? null : new ExecRpt(cPtr, false);
  }

  public int count() {
    return gmtradeJNI.ExecRptDataArray_count(swigCPtr, this);
  }

  public ExecRpt at(int i) {
    return new ExecRpt(gmtradeJNI.ExecRptDataArray_at(swigCPtr, this, i), false);
  }

  public void release() {
    gmtradeJNI.ExecRptDataArray_release(swigCPtr, this);
  }

}
