/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.td;

public class gmtrade {
  public static long getLEN_TRADE_SYMBOL() {
    return gmtradeJNI.LEN_TRADE_SYMBOL_get();
  }

  public static long getLEN_ID() {
    return gmtradeJNI.LEN_ID_get();
  }

  public static long getLEN_NAME() {
    return gmtradeJNI.LEN_NAME_get();
  }

  public static long getLEN_INFO() {
    return gmtradeJNI.LEN_INFO_get();
  }

}
