/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.ft.api.gm.td;

public class Position {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Position(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Position obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gmtradeJNI.delete_Position(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAccount_id(String value) {
    gmtradeJNI.Position_account_id_set(swigCPtr, this, value);
  }

  public String getAccount_id() {
    return gmtradeJNI.Position_account_id_get(swigCPtr, this);
  }

  public void setAccount_name(String value) {
    gmtradeJNI.Position_account_name_set(swigCPtr, this, value);
  }

  public String getAccount_name() {
    return gmtradeJNI.Position_account_name_get(swigCPtr, this);
  }

  public void setSymbol(String value) {
    gmtradeJNI.Position_symbol_set(swigCPtr, this, value);
  }

  public String getSymbol() {
    return gmtradeJNI.Position_symbol_get(swigCPtr, this);
  }

  public void setSide(int value) {
    gmtradeJNI.Position_side_set(swigCPtr, this, value);
  }

  public int getSide() {
    return gmtradeJNI.Position_side_get(swigCPtr, this);
  }

  public void setVolume(long value) {
    gmtradeJNI.Position_volume_set(swigCPtr, this, value);
  }

  public long getVolume() {
    return gmtradeJNI.Position_volume_get(swigCPtr, this);
  }

  public void setVolume_today(long value) {
    gmtradeJNI.Position_volume_today_set(swigCPtr, this, value);
  }

  public long getVolume_today() {
    return gmtradeJNI.Position_volume_today_get(swigCPtr, this);
  }

  public void setVwap(double value) {
    gmtradeJNI.Position_vwap_set(swigCPtr, this, value);
  }

  public double getVwap() {
    return gmtradeJNI.Position_vwap_get(swigCPtr, this);
  }

  public void setAmount(double value) {
    gmtradeJNI.Position_amount_set(swigCPtr, this, value);
  }

  public double getAmount() {
    return gmtradeJNI.Position_amount_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    gmtradeJNI.Position_price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return gmtradeJNI.Position_price_get(swigCPtr, this);
  }

  public void setFpnl(double value) {
    gmtradeJNI.Position_fpnl_set(swigCPtr, this, value);
  }

  public double getFpnl() {
    return gmtradeJNI.Position_fpnl_get(swigCPtr, this);
  }

  public void setCost(double value) {
    gmtradeJNI.Position_cost_set(swigCPtr, this, value);
  }

  public double getCost() {
    return gmtradeJNI.Position_cost_get(swigCPtr, this);
  }

  public void setOrder_frozen(long value) {
    gmtradeJNI.Position_order_frozen_set(swigCPtr, this, value);
  }

  public long getOrder_frozen() {
    return gmtradeJNI.Position_order_frozen_get(swigCPtr, this);
  }

  public void setOrder_frozen_today(long value) {
    gmtradeJNI.Position_order_frozen_today_set(swigCPtr, this, value);
  }

  public long getOrder_frozen_today() {
    return gmtradeJNI.Position_order_frozen_today_get(swigCPtr, this);
  }

  public void setAvailable(long value) {
    gmtradeJNI.Position_available_set(swigCPtr, this, value);
  }

  public long getAvailable() {
    return gmtradeJNI.Position_available_get(swigCPtr, this);
  }

  public void setAvailable_today(long value) {
    gmtradeJNI.Position_available_today_set(swigCPtr, this, value);
  }

  public long getAvailable_today() {
    return gmtradeJNI.Position_available_today_get(swigCPtr, this);
  }

  public void setAvailable_now(long value) {
    gmtradeJNI.Position_available_now_set(swigCPtr, this, value);
  }

  public long getAvailable_now() {
    return gmtradeJNI.Position_available_now_get(swigCPtr, this);
  }

  public void setLast_price(double value) {
    gmtradeJNI.Position_last_price_set(swigCPtr, this, value);
  }

  public double getLast_price() {
    return gmtradeJNI.Position_last_price_get(swigCPtr, this);
  }

  public void setLast_volume(long value) {
    gmtradeJNI.Position_last_volume_set(swigCPtr, this, value);
  }

  public long getLast_volume() {
    return gmtradeJNI.Position_last_volume_get(swigCPtr, this);
  }

  public void setLast_inout(long value) {
    gmtradeJNI.Position_last_inout_set(swigCPtr, this, value);
  }

  public long getLast_inout() {
    return gmtradeJNI.Position_last_inout_get(swigCPtr, this);
  }

  public void setChange_reason(int value) {
    gmtradeJNI.Position_change_reason_set(swigCPtr, this, value);
  }

  public int getChange_reason() {
    return gmtradeJNI.Position_change_reason_get(swigCPtr, this);
  }

  public void setChange_event_id(String value) {
    gmtradeJNI.Position_change_event_id_set(swigCPtr, this, value);
  }

  public String getChange_event_id() {
    return gmtradeJNI.Position_change_event_id_get(swigCPtr, this);
  }

  public void setHas_dividend(int value) {
    gmtradeJNI.Position_has_dividend_set(swigCPtr, this, value);
  }

  public int getHas_dividend() {
    return gmtradeJNI.Position_has_dividend_get(swigCPtr, this);
  }

  public void setCreated_at(long value) {
    gmtradeJNI.Position_created_at_set(swigCPtr, this, value);
  }

  public long getCreated_at() {
    return gmtradeJNI.Position_created_at_get(swigCPtr, this);
  }

  public void setUpdated_at(long value) {
    gmtradeJNI.Position_updated_at_set(swigCPtr, this, value);
  }

  public long getUpdated_at() {
    return gmtradeJNI.Position_updated_at_get(swigCPtr, this);
  }

  public Position() {
    this(gmtradeJNI.new_Position(), true);
  }

}
