/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_gmdata_WRAP_H_
#define SWIG_gmdata_WRAP_H_

class SwigDirector_Data : public gmdata::Data, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Data(JNIEnv *jenv, char const *token);
    SwigDirector_Data(JNIEnv *jenv);
    virtual ~SwigDirector_Data();
    virtual void on_tick(Tick *tick);
    virtual void on_bar(Bar *bar);
    virtual void on_error(int error_code, char const *error_msg);
    virtual void on_market_data_connected();
    virtual void on_market_data_disconnected();
public:
    bool swig_overrides(int n) {
      return (n < 5 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<5> swig_override;
};


#endif
